apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ko7mtm5z6-python-gitops
  description: This is GitOps manifest for ko7mtm5z6-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ko7mtm5z6-python
    backstage.io/kubernetes-id: ko7mtm5z6-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ko7mtm5z6-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ko7mtm5z6-python
