apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ko7mtm5z6-python
  janus-idp.io/tekton: ko7mtm5z6-python
  backstage.io/kubernetes-id: ko7mtm5z6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ko7mtm5z6-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
